version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: balbino
      POSTGRES_PASSWORD: balbino
      POSTGRES_DB: aluraflix
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"