spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aluraflix
    username: balbino
    password: balbino
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

aluraflix_secret: ${JWT_SECRET:secret}